process.on('uncaughtException', err => {
  console.log(`ðŸš« Unhandled exception: ${err.stack}`);
});

process.on('unhandledRejection', reason => {
  console.log(
    `ðŸš« Unhandled Promise rejection: ${reason instanceof Error ? reason.stack : reason}`
  );
});
